config/routes.rb
Editor::Application.routes.draw do
  resources :documents
  resources :howlers
  root :to => "documents#index"
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :body, :title, :requester, :word_count

  default_scope order("updated_at DESC")

  def to_pusher
    {
      id:         self.id.to_s,
      title:      self.title,
      body:       self.body,
      updated_at: self.updated_at
    }
  end
end

app/models/document_observer.rb
class DocumentObserver < ActiveRecord::Observer
  def after_create(document)
    Notifier.requested_document_start(document).deliver unless document.requester.blank?
  end
end

app/models/howler.rb
class Howler < ActiveRecord::Base
  attr_accessor :recipient_addresses
  attr_accessible :charges, :notes, :recipient_addresses

  after_initialize :default_values
  before_validation :make_url_token, if: :new_record?
  before_validation :merge_recipient_list

  validates_presence_of :url, :charges
  validates_uniqueness_of :url
  validates_numericality_of :charges, greater_than_or_equal_to: 1, if: :new_record?

  serialize :recipient_list

  def played?
    !played_at.nil?
  end

  def new_recipients
    return [] unless recipient_list
    recipient_list.
      reject { |recipient, sent| sent }.
      map { |recipient, sent| recipient }
  end

  def default_values
    self.charges ||= 1
    self.recipient_addresses = recipient_list.keys.join(", ") if recipient_list
  end

  def make_url_token
    self.url = SecureRandom.hex(32)
  end

  def merge_recipient_list
    self.recipient_list ||= {}
    self.recipient_list = make_recipient_list(recipient_addresses).merge recipient_list
  end

  def make_recipient_list(addresses)
    Hash[ addresses.split(/\s*,\s*/).collect { |address| [address, nil] } ]
  end
end

app/models/howler_observer.rb
class HowlerObserver < ActiveRecord::Observer
  def after_save(howler)
    howler.new_recipients.each do |recipient|
      Notifier.new_howler(recipient, howler).deliver
      howler.recipient_list[ recipient] = true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with :name => ENV['EDITOR_USERNAME'], :password => ENV['EDITOR_PASSWORD']
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  respond_to :json, only: [:update]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.select([:id, :title, :word_count, :updated_at, :requester])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to edit_document_path(@document), notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params[:document])
      Pusher.trigger(pusher_channel, 'update', @document.to_pusher)
    end
    respond_with @document
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private

  def pusher_channel
    "#{Rails.env}_main_channel"
  end
end

app/controllers/howlers_controller.rb
class HowlersController < ApplicationController

  def index
    @howlers = Howler.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @howler= Howler.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new 
    @howler = Howler.new
  end

  def edit
    @howler = Howler.find(params[:id])
  end

  def create 
    @howler = Howler.new(params[:howler])
    respond_to do |format|
      if @howler.save
        format.html { redirect_to @howler, notice: 'Howler was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update 
    @howler = Howler.find(params[:id])
    respond_to do |format|
      if @howler.update_attributes(params[:howler])
        format.html { render action: "show" }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @howler = Howler.find(params[:id])
    @howler.destroy

    respond_to do |format|
      format.html { redirect_to howlers_url }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title_or_default(title)
    return title unless title.blank?
    "<em>Untitled</em>"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/_form.html.haml
= form_for @document, html: { class: "form-horizontal" } do |f|
  - if @document.errors.any?
    #error_explanation
      %h2= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg

  .row
    .span6
      .control-group
        = f.label :title, class: "control-label"
        .controls
          = f.text_field :title, placeholder: "Untitled"
          - unless @document.new_record?
            #connection-status.label
              Initialising...
      .control-group
        = f.label :requester, class: "control-label"
        .controls
          - if @document.new_record?
            .input-prepend
              %span.add-on
                %i.icon-envelope
              = f.text_field :requester, placeholder: "email address"
          - else
            %span.uneditable-input.input= @document.requester
    .span6
      - unless @document.new_record?
        .control-group
          = f.label :word_count, class: "control-label"
          .controls
            = f.number_field :word_count, value: @document.word_count, class: "uneditable-input input", readonly: "readonly"
  .row
    .span12
      - if @document.new_record?
        .control-group
          .controls
            = f.submit class: "btn"
      - else
        .control-group
          = f.label :body, class: "control-label"
          .controls
            = f.text_area :body, id: 'redactor'

- content_for :navigation do
  %li
    = link_to new_document_path do
      %i.icon-file
      New Document

app/views/documents/edit.html.haml
= render 'form'

- content_for :end_javascript do
  :javascript
    App.require('documents/edit', {})

app/views/documents/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Title
      %th Words
      %th Requester
      %th Last Updated
      %th

  %tbody
    - @documents.each do |document|
      %tr
        %td
          = link_to edit_document_path(document) do
            %i.icon-pencil
            = raw title_or_default(document.title)
        %td= document.word_count
        %td= document.requester
        %td= time_tag document.updated_at, format: :short
        %td
          = link_to document, method: :delete, data: { confirm: 'Are you sure?' } do
            %i.icon-trash

- content_for :navigation do
  %li
    = link_to new_document_path do
      %i.icon-file
      New Document

app/views/documents/new.html.haml
= render 'form'

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @document.title
%p
  %b Body:
  = raw @document.body

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path

app/views/howlers/_actions.html.haml
= link_to edit_howler_path(howler) do
  %i.icon-pencil
= link_to howler, method: :delete, data: { confirm: 'Are you sure?' } do
  %i.icon-trash

app/views/howlers/_form.html.haml
= form_for @howler, html: { class: "form-horizontal" } do |f|
  - if @howler.errors.any?
    #error_explanation
      %h2= "#{pluralize(@howler.errors.count, "error")} prohibited this howler from being saved:"
      %ul
        - @howler.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :charges, class: "control-label"
    .controls
      = f.number_field :charges, value: @howler.charges, class: "input"
  .control-group
    = f.label :recipient_addresses, class: "control-label"
    .controls
      = f.text_field :recipient_addresses, value: @howler.recipient_addresses, class: "input", placeholder: "recipient1@example.com, recipient@example.com ..."
  .control-group
    = f.label :notes, class: "control-label"
    .controls
      = f.text_area :notes, rows: 3
  .control-group
    .controls
      = f.submit class: "btn"

app/views/howlers/edit.html.haml
%h1 Edit Howler
= render 'form'

app/views/howlers/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Id
      %th Notes
      %th Charges left
      %th Created at
      %th Last used at
      %th Actions
  %tbody
    - @howlers.each do |howler|
      %tr
        %td
          = link_to howler do
            = howler.id
        %td
          = link_to howler do
            = simple_format howler.notes
        %td= howler.charges
        %td= time_tag howler.created_at, format: :short
        %td= howler.played? ? time_tag(howler.played_at, format: :short) : "-"
        %td
          = render partial: "actions", locals: { howler: howler }

- content_for :navigation do
  %li
    = link_to new_howler_path do
      %i.icon-file
      New Howler

app/views/howlers/new.html.haml
%h1 New Howler

= render 'form'

app/views/howlers/show.html.haml
%h2 Howler ##{@howler.id}
.actions
  = render partial: "actions", locals: { howler: @howler }

%p
  This howler was created on
  = time_tag @howler.created_at, format: :long
  and still has
  = @howler.charges
  charges left.
%p
  - if @howler.played? 
    It has been used for the last time on
    = time_tag @howler.played_at, format: :long
  - else
    This howler never played yet.

%h3 Secret URL
%p
  The url that will activate this Howler is...
%pre
  http://100hours.tv/howl/#{@howler.url}


%blockquote
  %p
    = simple_format @howler.notes

%h3 Recipients
%p
  To add more recipients, 
  = link_to "edit this howler", edit_howler_path(@howler)
%table.table.table-condensed
  %thead
    %tr
      %th Email
      %th Message sent?
  %tbody
    - @howler.recipient_list.each do |recipient, sent|
      %tr
        %td= recipient
        %td= sent

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Editor", root_path, :class => 'brand'
.nav-collapse.collapse
  %ul.nav
    %li
      = link_to "Howlers", howlers_path
    %li
      = link_to "Documents", documents_path
    = yield :navigation
    %li
      %audio{ src: "/audios/inception.mp3" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Editor"
    %meta{:content => content_for?(:description) ? yield(:description) : "Editor", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main
    = yield :end_javascript

app/views/notifier/new_howler.text.erb
Hi,
Thank you for your donation!

Because you've been so generous, you've been granted the chance to give David a little extra encouragement - if, for example, you notice he's falling asleep or daydreaming too much.

When you think the moment is right, click on the link below to send a (very) loud honk that will no doubt startle David and get him motivated again:

http://100hours.tv/howl/<%= @howler.url %>

It will only work once, so choose your moment wisely!

Kind regards,
  The 100hours.tv team

app/views/notifier/requested_document_start.text.erb
Hi,

This is an automated message to let you know that David has started writing the piece you requested for the 100 Hours of Solitude initiative. He started writing on <%= @document.created_at.to_formatted_s(:long) %> and the working title is “<%= @document.title %>”. You can watch him writing live by going to http://100hours.tv, where you will also find the other pieces that David has created so far.
Thanks again for your support,

The 100hours.tv team